### ISSUE TITLE
缺少AuthAction文件

### ISSUE THREAD

**Issue by cy3329520** [somowhere/albedo-cloud#1]
com.alibaba.csp.sentinel.dashboard.auth.AuthAction目录下，缺少AuthAction文件

**Comment by cy3329520** [comment]
在albedo-modules的albedo-sentinel下面，没有这个文件

**Comment by cy3329520** [comment]
还缺少com.alibaba.csp.sentinel.dashboard.auth.AuthorizationInterceptor
和com.alibaba.csp.sentinel.dashboard.auth.LoginAuthenticationFilter

**Comment by somowhere** [comment]
已经提交
