### ISSUE TITLE
部门编辑、删除、修改等操作之后没有更新缓存

### ISSUE THREAD

**Issue by tan9710630** [somowhere/albedo-cloud#3]
由于没有更新缓存，导致部门更新之后用户编辑无法获取最新的部门结构

**Comment by somowhere** [comment]
fix in 64aaaf439f675c7f9d0b7c739dd2e221fd6933d0[https://github.com/somowhere/albedo-cloud/commit/64aaaf439f675c7f9d0b7c739dd2e221fd6933d0](url)
