### ISSUE TITLE
RemoteRoleService之中的findDeptIdsByRoleId没有远程实现

### ISSUE THREAD

**Issue by tan9710630** [somowhere/albedo-cloud#4]
远程调用findDeptIdsByRoleId失败，401，原因是sys之中没有对应的接口实现

**Comment by somowhere** [comment]
fix in 64aaaf439f675c7f9d0b7c739dd2e221fd6933d0[https://github.com/somowhere/albedo-cloud/commit/64aaaf439f675c7f9d0b7c739dd2e221fd6933d0](url)

**Comment by somowhere** [comment]
fix in 64aaaf439f675c7f9d0b7c739dd2e221fd6933d0[https://github.com/somowhere/albedo-cloud/commit/64aaaf439f675c7f9d0b7c739dd2e221fd6933d0](url)
